apiVersion: apps/v1
kind: Deployment
metadata:
  name: diplom-nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: yaremko-test-nginx
        image: insommnia/yaremko-test-nginx:v2
        ports:
        - containerPort: 80
